theme: jekyll-theme-slate
title: Machine Learning for Creativity and Design
description: NeurIPS 2019 Workshop, Vancouver, Canada
# eventdate: Saturday December 8ᵗʰ 8:30 &#8212; 18:15  # TODO: change the date when we know. Dec 13 or 14.
